config/routes.rb
Rails.application.routes.draw do
  root to: "trips#index"
  resources :trips do
    resources :items
    resources :missions
    resources :memos
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :trip

  with_options presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/} do
    validates :name
  end
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :trip

  with_options presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/} do
    validates :text
  end
end

app/models/mission.rb
class Mission < ApplicationRecord
  belongs_to :trip

  with_options presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/} do
    validates :name
  end
end

app/models/trip.rb
class Trip < ApplicationRecord
  has_many :items, dependent: :destroy
  has_many :memos, dependent: :destroy
  has_many :missions, dependent: :destroy
  
  with_options presence: true, format: { with: /\A[ぁ-んァ-ン一-龥]/} do
    validates :name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
    @item = Item.new
    @trip = Trip.find(params[:trip_id])
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @trip = Trip.find(params[:trip_id])
      if @item.valid?
         @item.save
         redirect_to controller: :trips, action: :show, id: @trip.id
      else
        render "index"
      end
  end

  def destroy
    @trip = Trip.find(params[:trip_id])
    item = @trip.items.find(params[:id])
    item.destroy
    redirect_to controller: :trips, action: :show, id: @trip.id
  end

  private

  def item_params
    params.permit(:name, :trip_id)
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  def index
    @memos = Memo.all
    @memo = Memo.new
    @trip = Trip.find(params[:trip_id])
  end

  def new
    @memo = Memo.new
  end

  def create
    @memo = Memo.new(memo_params)
    @trip = Trip.find(params[:trip_id])
      if @memo.valid?
         @memo.save
         redirect_to controller: :trips, action: :show, id: @trip.id
      else
        render "index"
      end
  end

  def destroy
    @trip = Trip.find(params[:trip_id])
    memo = @trip.memos.find(params[:id])
    memo.destroy
    redirect_to controller: :trips, action: :show, id: @trip.id
  end

  private

  def memo_params
    params.permit(:text, :trip_id)
  end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  def index
    @missions = Mission.all
    @mission = Mission.new
    @trip = Trip.find(params[:trip_id])
  end

  def new
    @mission = Mission.new
  end

  def create
    @mission = Mission.new(mission_params)
    @trip = Trip.find(params[:trip_id])
      if @mission.valid?
         @mission.save
         redirect_to controller: :trips, action: :show, id: @trip.id
      else
        render "index"
      end
  end

  def destroy
    @trip = Trip.find(params[:trip_id])
    mission = @trip.missions.find(params[:id])
    mission.destroy
    redirect_to controller: :trips, action: :show, id: @trip.id
  end

  private

  def mission_params
    params.permit(:name, :trip_id)
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def index
    @trips = Trip.all
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.create(trip_params)
      if @trip.valid?
        @trip.save
        redirect_to trip_path(@trip.id)
      else
        render "new"
      end
  end

  def show
    @trip = Trip.find(params[:id])    
    @items = @trip.items
    @missions = @trip.missions
    @memos = @trip.memos
  end

  def destroy
    trip = Trip.find(params[:id])
    trip.destroy
    redirect_to root_path
  end

  private
  def trip_params
    params.require(:trip).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/items/index.html.erb
<div class="item-main">
 <h1 class="item-messeage">何を持って行きますか？</h1>
  <%= form_with url: trip_items_path, local: true  do |f| %>
   <%= render 'shared/error_messages', model: @item %>
   <div class="item-form">
    <%= f.text_field :name, id:"content", placeholder:"(例)財布"%>
    <%= f.submit '登録する' , id: "submit" %>
    <br><%=link_to '(Topへ)', root_path, class:"back-item" %>
   </div>
  <% end %>
  <div id="list">
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tabilog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/memos/index.html.erb
 <div class="todo-main">
 <h1 class="todo-messeage">備忘録を書こう</h1>
  <%= form_with url: trip_memos_path, local: true do |f| %>
   <%= render 'shared/error_messages', model: @memo %>
   <div class="todo-form">
    <%= f.text_field :text, id:"content", placeholder:"気になった事をメモ"%>
    <%= f.submit '登録する' , id: "submit" %>
    <br><%=link_to '(Topへ)', root_path, class:"back-item" %>
   </div>
  <% end %>
  <div id="list">
  </div>
 </div>

app/views/missions/index.html.erb
 <div class="todo-main">
 <h1 class="todo-messeage">あなたは現地でどんな「０→１」体験をしますか？</h1>
  <%= form_with url: trip_missions_path, local: true do |f| %>
   <%= render 'shared/error_messages', model: @mission %>
   <div class="todo-form">
    <%= f.text_field :name, id:"content", placeholder:"(例)名産品を買う"%>
    <%= f.submit '登録する' , id: "submit" %>
    <br><%=link_to '(Topへ)', root_path, class:"back-mission" %>
   </div>
  <% end %>
  <div>
  </div>
 </div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/trips/index.html.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>旅Log</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="ここにサイト説明を入れます">
  <meta name="keywords" content="キーワード１,キーワード２,キーワード３,キーワード４,キーワード５">
  <link rel="stylesheet" href="stylesheets/trips.css">
  <script src="javascript/fixmenu_pagetop.js"></script>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script>
  $(function(){
  $('a[href^="#"]').click(function() {
  var speed = 800;
  var href= $(this).attr("href");
  var target = $(href == "#" || href == "" ? 'html' : href);
  var position = target.offset().top;
  $('body,html').animate({scrollTop:position}, speed, 'swing');
  return false;
  });
  });
  </script>
</head>

<body>

<header>
  <h1 id="logo"><%= image_tag 'logo.png' %></h1>
  <nav id="menubar">
    <ul>
      <li class="top-mes"><a href="#company">旅行先を登録</a></li>
    </ul>
  </nav>
</header>

<div id="container">

<div id="contents">

<section id="company">

<h2>旅行先 <%= link_to '(登録)', new_trip_path, class: 'btn trip' %></h2>

<div class="trip-boss">
    <div class="trip-box">
      <% @trips.each do |trip| %>
      <p><%= link_to trip.name, trip_path(trip.id), class: "trip_name" %><%= link_to '(削除)', trip_path(trip.id), method: :delete, class:'delete' %></p>
      <% end %>
    </div>
</div>

</section>

</body>
</html>

app/views/trips/new.html.erb
<div class="trip-place">
  <div class="container">
    <h3 class="trip-ab">旅行先は？</h3>
    <%= form_with(model: @trip, local: true) do |form| %>
      <%= render 'shared/error_messages', model: form.object %>
      <%= form.text_field :name, placeholder: "旅行先" %>
      <%= form.submit "登録する" %>
    <% end %>
  </div>
  <%=link_to 'もどる', root_path, class:"#" %>
</div>

app/views/trips/show.html.erb
<div class="item-register">
 <div class = "trip-name">
  <h1>旅行先：<%=  @trip.name %><%=link_to '(Topへ)', root_path, class:"back" %></h1>
 </div>
  <div class='total_btn'>
    <div class = "item btn">
      <%= link_to  "持ち物", trip_items_path(@trip.id), method: :get, class:"btn-gradient-3d-simple" %>
    </div>
    <div class = "item-list">
      <% @items.each do |item| %>
          <li class="item-text">
           <input type="checkbox"> <span class="strikethrough"><%= item.name %></span><%= link_to '(削除)', trip_item_path(@trip.id, item), method: :delete, class:'mix' %>

          </li>
      <% end %> 
    </div>
    <div class = "todo_btn">
      <%= link_to "ミッション", trip_missions_path(@trip.id), method: :get, class:"btn-gradient-2d-simple" %>
    </div>
    <div class="todo-list">
      <% @missions.each do |mission| %>
         <li class="todo-text">
          <input type="checkbox"><span class="strikethrough"><%= mission.name %></span><%= link_to '(削除)', trip_mission_path(@trip.id, mission), method: :delete, class:'test' %>
         </li>
      <% end %> 
    </div>
    <div class = "todo_btn">
      <%= link_to "備忘録", trip_memos_path(@trip.id), method: :get, class:"btn-gradient-1d-simple" %>
    </div>
    <div class="todo-list">
      <% @memos.each do |memo| %>
         <li class="memo-text">
          ・<%= memo.text %><%= link_to '(削除)', trip_memo_path(@trip.id, memo), method: :delete, class:'test' %>
         </li>
      <% end %> 
    </div>
  </div>
</div>